### PR TITLE
support passing through a theme object to override Lightbox styles

### PR DESCRIPTION
**Pull request by danalloway**
`react-images` <Lightbox /> supports taking a `theme` prop which allows for modifying the styles it uses, this PR exposes the theme prop for `react-grid-gallery` so users can tweak the theme.

### CODE REVIEW

**Comment by benhowell** [comment]
Thanks @danalloway, will merge shortly. I'll also do a new release including this merge after I update the docs, etc. :+1:

**Comment by am** [comment]
Nice to see this got merged, but the documentation for this feature looks like to be missing...

**Comment by benhowell** [comment]
Wow, how did I miss that?! Thanks... I'll get that fixed 😀

**Comment by subhamchatterjee** [comment]
> Wow, how did I miss that?! Thanks... I'll get that fixed

Hey waiting for the documentation of implementing the theme prop.

**Pull request merged**
