### PR TITLE
Add description image property

### PR DESCRIPTION
**Pull request by jakub-tucek**
Hey, like this library. One thing I am missing is option to add image description, so I implemented it (with demo).

Please let me known, if it's ok to use it or I will have to use fork / find another lib in future. Thanks.

Cheers

### CODE REVIEW

**Comment by benhowell** [comment]
Hi,
Can you describe in greater detail what this feature does? Have you got a demo I can see?

Thanks.

**Comment by jakub-tucek** [comment]
Hi, 

There is demo5 in PR. Or you want some kond of direct link?

This pr adds option to add description (string or element) to object representing image. Description is then shown below image. 

For example: in my case, I need to show title of image and author name. (And cant do it in overlay)

**Comment by benhowell** [comment]
Link or screenshot would be good as it saves me from merging the pull request, then packaging and deploying to test in order to see the demo ;-)

**Comment by jakub-tucek** [comment]
Here is screenshot from new demos page:

image

**Comment by benhowell** [comment]
Thanks very much for that.
I've changed the prop name from description to thumbnailCaption for consistency with the other props.

Released in [v0.4.4](https://github.com/benhowell/react-grid-gallery/releases/tag/v0.4.4) :+1:

**Pull request merged**
