### PR TITLE
Tags and caption element

### PR DESCRIPTION
**Pull request by Igor-Palaguta**
Ability to specify caption and tags as elements

### CODE REVIEW

**Comment by benhowell** [comment]
Thanks Igor. Merged. I'll cut a new release soon.

**Comment by Igor-Palaguta** [comment]
Hi @benhowell 
Looks like I forgot to change README. Should I perform new PR?

**Comment by benhowell** [comment]
Yes, another PR would be great. Thanks!

**Comment by garciawell** [comment]
@benhowell 

Hello, I found a bug where when adding an element in the caption,  the title of the image shown as [object object]. I noticed there is already a fix for this. Do you have a forecast for when it will be implemented?

react-grid

**Pull request merged**
