### PR TITLE
Add option to render a custom overlay on a tile when hover

### PR DESCRIPTION
**Pull request by ValYouW**
What do you think about this? Basically it let user to render their own overlay when hovering an image, this let me do this:
customoverlay

The Image component just renders a full-sized div and setting the opacity based on the hover state, it is the user's responsibility to style the overlay.

Thx

### CODE REVIEW

**Comment by benhowell** [comment]
Very nice :+1: 
Do you have something live I can take a look at?

**Comment by ValYouW** [comment]
Not available right now only on my laptop, I'll see if I can put something together on codepen

**Comment by benhowell** [comment]
That'd be great!

**Comment by ValYouW** [comment]
Added example to the examples page, you can see it here (towards the end, look for "custom overlay")
https://valyouw.github.io/react-grid-gallery/

**Comment by ValYouW** [comment]
Ah, looks like it prevents from LightBox to open....!

**Comment by benhowell** [comment]
Thanks @ValYouW :+1: 
I've merged your pull request and will make a few changes and update the demo before I release v0.3.3.

**Comment by benhowell** [comment]
Included in release v0.3.3

**Comment by ValYouW** [comment]
Great, Thx.

**Pull request merged**
